### ISSUE TITLE
[Errno 22] Invalid argument in read_sp2b.py

### ISSUE THREAD

**Issue by bsumlin** [ARM-DOE/PySP2#1]
Thanks very much for this promising module! When I try to read in an sp2b file, I get the following error:

```
  File "C:\ProgramData\Anaconda3\lib\site-packages\pysp2-0.1.0-py3.7.egg\pysp2\io\read_sp2b.py", line 104, in read_sp2
    DateTimeWave = datetime.timestamp(dt) + TimeWave - datetime.timestamp(datetime(1904, 1, 1))

OSError: [Errno 22] Invalid argument
```

EDIT: I'm running Python 3 on a Windows installation. This *may* be a result of Windows not supporting Unix-like timestamps prior to 1970. If PySP2 was developed and tested on a non-Windows platform, that may be a place to investigate. I'll try to contribute a fix and submit a pull request if I come up with anything.

https://stackoverflow.com/questions/59199985/why-is-datetimes-timestamp-method-returning-oserror-errno-22-invalid-a?noredirect=1&lq=1

**Comment by rcjackson** [comment]
I'm about to push some updates to PySP2. I recall encountering an issue with date times in Windows when I tested PySP2 out there, so you may want to pull from the newest code.

**Comment by AdamTheisen** [comment]
@rcjackson can we close this out then?
