### ISSUE TITLE
Time values in read_sp2

### ISSUE THREAD

**Issue by mdpetters** [ARM-DOE/PySP2#34]
Thanks for putting together this nice package. I was "stealing" the ```read_sp2``` function to load binary files into Julia via PyCall, to the process the raw data further. The binary decoder is great.

While doing so, I noticed a potential issue with the time stamp. First, here is one of our data files loaded in python. The system is running 24/7 and the file is the first file of the day. Therefore, the first time index should be close to ```00:00:00```. However, it appears as  ```2022-07-04T02:00:00.043457``` 

```py
>>> my_sp2 = pysp2.io.read_sp2(file, arm_convention = False) 
>>> my_sp2
<xarray.Dataset>
Dimensions:          (event_index: 50003, columns: 100)
Dimensions without coordinates: event_index, columns
Data variables: (12/19)
    time             (event_index) datetime64[ns] 2022-07-04T02:00:00.043457 ...
    Flag             (event_index) int16 16 16 16 16 16 16 ... 16 16 32 25 16 16
    Res1             (event_index) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    Res5             (event_index) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    Res6             (event_index) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    Res7             (event_index) float64 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    ...               ...
    Data_ch2         (event_index, columns) int64 -29484 -29472 ... -29504
    Data_ch3         (event_index, columns) int64 420 692 648 ... 344 692 260
    Data_ch4         (event_index, columns) int64 -27556 -27564 ... -27552
    Data_ch5         (event_index, columns) int64 -29432 -29432 ... -29424
    Data_ch6         (event_index, columns) int64 -29408 -29412 ... -29416
    Data_ch7         (event_index, columns) int64 -44 -76 -64 32 ... -40 -76 -28
>>> 
```

When I take the first ```DateTimeWaveUTC``` value, I get this.

```py
>>> my_sp2.DateTimeWaveUTC.to_index()[1]
3739737600.043457
>>> 
```

I happen to had my own LabView timestamp to DateTime function from a different project written in Julia.

```julia
function labview2julia(t) 
	basetime = Dates.value(DateTime(1904,1,1,0,0,0))
	return t*1000.0 |> round |> x -> convert(DateTime, Millisecond(x + basetime))
end
```

Applying this function to the first DateTimeWaveUTC value gives the apparently correct ```00:00:00``` timestamp. 

```julia
julia> labview2julia(3739737600.043457)
2022-07-04T00:00:00.043
```

It would thus seem to me that there is a 2 h bias in the conversion in ```read_sp2```. I read through the python code, but couldn't quite find an obvious reason for this behavior. Am I missing anything obvious here?

**Comment by AdamTheisen** [comment]
@rcjackson have you had a chance to check this out?

**Comment by johbackm** [comment]
Maybe I can try and comment on this. The SP2 software starts a new file when the computer's clock hits 00:00:00. Both `my_sp2.time` (shown in your example above) and `my_sp2.DateTimeWaveUTC` are in UTC 0. So for your experiment to work, do it on `my_sp2.DateTimeWave.to_index()[0]` and not on `my_sp2.DateTimeWaveUTC.to_index()[0]` since only my_sp2.DateTimeWave.to_index()[0] will be close to 00:00:00 if the computer's clock isn't in UTC 0. The SP2 software keeps track on both local and UTC time and those are handled independently in `pysp2.io.read_sp2()`. Are you sure you got 3739737600.043457 from `my_sp2.DateTimeWaveUTC.to_index()[1]` and not from `my_sp2.DateTimeWave.to_index()[1]` as  it seems to be close to 00:00:00 as far as I can tell.

**Comment by rcjackson** [comment]
The time is being returned in the machine's local time instead of UTC. I've put in a PR to fix this. This doesn't affect any of the mass and particle size distribution products since that processing uses DateTimeWaveUTC to get the particle times.
